# この章の目的

この章では、NumPyでデータ(行列)を扱う基本的な方法を学びます

## 内容

- 1次元データ(array)
- 2次元データ(array)
- 変形(reshape)
- データ型(dtype)
- スライス
- データ再代入
- 深いコピー(copy)
- range (arange)
- 乱数
- ゼロ埋める
- 1埋める
- 単位行列
- 指定値で埋める
- 範囲指定でデータを作る (linspace)
- 連結
- 分割
- 転置
- 次元追加

In [1]:
import numpy as np

### 1次元データ

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

### 2次元データ

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

### 変形(reshape)

In [7]:
c1 = np.array([0, 1, 2, 3, 4, 5])

In [8]:
c1

array([0, 1, 2, 3, 4, 5])

In [9]:
c2 = c1.reshape([2, 3])

In [15]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
c3 = c2.ravel()

In [12]:
c3

array([0, 1, 2, 3, 4, 5])

In [20]:
c4 = c2.flatten()  # copy を返す

In [19]:
c4

array([0, 1, 2, 3, 4, 5])

## データ型

In [13]:
a.dtype

dtype('int64')

In [14]:
d = np.array([1, 2], dtype=np.int16)

In [15]:
d

array([1, 2], dtype=int16)

In [16]:
d.dtype

dtype('int16')

In [17]:
d2 = d.astype(np.float16)

In [18]:
d2

array([ 1.,  2.], dtype=float16)

### スライス

In [19]:
a

array([1, 2, 3])

In [20]:
a[0]

1

In [21]:
a[1:]

array([2, 3])

In [22]:
a[-1]

3

In [23]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b[0]

array([1, 2, 3])

In [25]:
b[1, 0]

4

In [26]:
b[:, 2]

array([3, 6])

In [27]:
b[1, :]

array([4, 5, 6])

In [28]:
b[0, 1:]

array([2, 3])

In [21]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

### データ再代入

In [29]:
a

array([1, 2, 3])

In [30]:
a[2] = 4

In [31]:
a

array([1, 2, 4])

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b[1, 2] = 7

In [34]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [35]:
b[:, 2] = 8

In [36]:
b

array([[1, 2, 8],
       [4, 5, 8]])

### 深いコピー

In [37]:
a1 = a

In [38]:
a1

array([1, 2, 4])

In [39]:
a1[1] = 5

In [40]:
a1

array([1, 5, 4])

In [41]:
a

array([1, 5, 4])

In [42]:
a2 = a.copy()

In [43]:
a2[0] = 6

In [44]:
a2

array([6, 5, 4])

In [45]:
a

array([1, 5, 4])

### range

In [46]:
e = np.arange(10)

In [47]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
e1 = np.arange(1, 11)

In [49]:
e1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
e2 = np.arange(1, 11, 2)

In [51]:
e2

array([1, 3, 5, 7, 9])

### 乱数

In [24]:
f = np.random.random((3, 2))

In [25]:
f

array([[ 0.81443564,  0.71894488],
       [ 0.13377108,  0.94379981],
       [ 0.20447256,  0.6701666 ]])

In [26]:
f1 = np.random.randint(1, 10)

In [27]:
f1

7

In [28]:
f2 = np.random.randint(1, 10, (3, 3))

In [29]:
f2

array([[7, 4, 9],
       [4, 3, 3],
       [1, 8, 9]])

### ゼロ埋める

In [58]:
g = np.zeros(3)

In [59]:
g

array([ 0.,  0.,  0.])

In [60]:
g1= np.zeros([2, 3])

In [61]:
g1

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### 1埋める

In [62]:
h = np.ones(2)

In [63]:
h

array([ 1.,  1.])

In [64]:
h1 = np.ones([3, 4])

In [65]:
h1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### 単位行列

In [66]:
i = np.eye(3)

In [67]:
i

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 指定値で埋める

In [68]:
j = np.full(1, 3.14)

In [69]:
j

array([ 3.14])

In [70]:
j2 = np.full((2, 4), np.pi)

In [71]:
j2

array([[ 3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265]])

### 範囲指定でデータを作る

In [72]:
k = np.linspace(0, 1, 5)

In [73]:
k

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [74]:
k1 = np.linspace(0, np.pi, 20)

In [75]:
k1

array([ 0.        ,  0.16534698,  0.33069396,  0.49604095,  0.66138793,
        0.82673491,  0.99208189,  1.15742887,  1.32277585,  1.48812284,
        1.65346982,  1.8188168 ,  1.98416378,  2.14951076,  2.31485774,
        2.48020473,  2.64555171,  2.81089869,  2.97624567,  3.14159265])

### 連結

In [76]:
a

array([1, 5, 4])

In [77]:
a1

array([1, 5, 4])

In [78]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [79]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [80]:
b1 = np.array([[10], [20]])

In [81]:
b1

array([[10],
       [20]])

In [82]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [83]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [84]:
b2 = np.array([30, 60, 45])

In [85]:
b2

array([30, 60, 45])

In [86]:
b3 = np.vstack([b, b2])

In [87]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割

In [88]:
first, second = np.hsplit(b3, [2])

In [89]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [90]:
second

array([[ 8],
       [ 8],
       [45]])

In [91]:
first1, second1 = np.vsplit(b3, [2])

In [92]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [93]:
second1

array([[30, 60, 45]])

### 転置

In [94]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [95]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

### 次元追加

In [96]:
a

array([1, 5, 4])

In [97]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [98]:
a[:, np.newaxis]

array([[1],
       [5],
       [4]])