# この章の目的

NumPyで各種計算を行います。

## 内容

- UFunction
- BroadCast
- 演算、ドット積
- 統計値
- 判定・論理値

In [1]:
import numpy as np

In [2]:
a = np.arange(3)
b = np.arange(3, 9).reshape([2, 3])
c = np.arange(6).reshape([2, 3])
d = np.arange(6).reshape([3, 2])
e = np.arange(9).reshape([3, 3])
f = np.linspace(-1, 1, 10)

In [3]:
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)
print("f", f)

a: [0 1 2]
b: [[3 4 5]
 [6 7 8]]
c: [[0 1 2]
 [3 4 5]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [[0 1 2]
 [3 4 5]
 [6 7 8]]
f [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [4]:
print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)
print("e:", e.shape)
print("f:", f.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (3, 3)
f: (10,)


## UFunction
Universal Functions
日本語: TBD

In [5]:
f

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [6]:
np.abs(f)

array([ 1.        ,  0.77777778,  0.55555556,  0.33333333,  0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [7]:
np.sin(f)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [8]:
np.cos(f)

array([ 0.54030231,  0.71247462,  0.84960756,  0.94495695,  0.99383351,
        0.99383351,  0.94495695,  0.84960756,  0.71247462,  0.54030231])

In [9]:
a

array([0, 1, 2])

In [10]:
np.log(a)

/Users/terapyon/dev/ipython/env-datahandling/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718])

In [11]:
np.log(b)

array([[ 1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154]])

In [12]:
np.log10(b)

array([[ 0.47712125,  0.60205999,  0.69897   ],
       [ 0.77815125,  0.84509804,  0.90308999]])

In [13]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 ])

## BroadCast

In [14]:
a

array([0, 1, 2])

In [15]:
a + 10

array([10, 11, 12])

In [16]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [17]:
a + b

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [18]:
a1 = a[:, np.newaxis]

In [19]:
a1

array([[0],
       [1],
       [2]])

In [20]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [21]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
c.mean()

2.5

In [23]:
c - c.mean()

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [24]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [25]:
b * 2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [26]:
b ** 3

array([[ 27,  64, 125],
       [216, 343, 512]])

## 演算、ドット積

In [27]:
a

array([0, 1, 2])

In [28]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [29]:
a + b

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [30]:
a * b

array([[ 0,  4, 10],
       [ 0,  7, 16]])

In [31]:
b * a

array([[ 0,  4, 10],
       [ 0,  7, 16]])

In [32]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
b + c

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [34]:
b * c

array([[ 0,  4, 10],
       [18, 28, 40]])

In [35]:
c * b

array([[ 0,  4, 10],
       [18, 28, 40]])

In [36]:
b @ a

array([14, 23])

In [37]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [38]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
b @ d

array([[28, 40],
       [46, 67]])

In [40]:
d @ b

array([[ 6,  7,  8],
       [24, 29, 34],
       [42, 51, 60]])

In [41]:
np.dot(d, b)

array([[ 6,  7,  8],
       [24, 29, 34],
       [42, 51, 60]])

In [42]:
b / c

/Users/terapyon/dev/ipython/env-datahandling/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[  inf,  4.  ,  2.5 ],
       [ 2.  ,  1.75,  1.6 ]])

In [43]:
np.exp(-100)  # もっといい方法があった気がする

3.7200759760208361e-44

In [44]:
b / (c + np.exp(-100)) 

array([[  8.06435143e+43,   4.00000000e+00,   2.50000000e+00],
       [  2.00000000e+00,   1.75000000e+00,   1.60000000e+00]])

## 統計値

In [45]:
a

array([0, 1, 2])

In [46]:
a.mean()

1.0

In [47]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [48]:
b.mean()

5.5

In [49]:
b.mean(axis=0)

array([ 4.5,  5.5,  6.5])

In [50]:
b.mean(axis=1)

array([ 4.,  7.])

In [51]:
a.sum()

3

In [52]:
b.sum()

33

In [53]:
b.sum(axis=1)

array([12, 21])

In [54]:
a.max()

2

In [55]:
a.min()

0

In [56]:
np.min(a)

0

In [57]:
np.max(a)

2

In [58]:
np.median(a)

1.0

In [59]:
np.std(a)

0.81649658092772603

In [60]:
np.std(b)

1.707825127659933

In [61]:
np.std(b, axis=1)

array([ 0.81649658,  0.81649658])

## 判定・論理値

In [62]:
a > 1

array([False, False,  True], dtype=bool)

In [63]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [64]:
b > 4

array([[False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [65]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
c == 3

array([[False, False, False],
       [ True, False, False]], dtype=bool)

In [67]:
c != 3

array([[ True,  True,  True],
       [False,  True,  True]], dtype=bool)

In [68]:
np.count_nonzero(c > 3)

2

In [69]:
np.sum(c > 3)

2

In [70]:
np.any(c > 2)

True

In [71]:
np.any(c > 10)

False

In [72]:
np.all(c > 2)

False

In [73]:
np.all(c >= 0)

True

In [74]:
a

array([0, 1, 2])

In [75]:
a > 1

array([False, False,  True], dtype=bool)

In [76]:
a[a > 1]

array([2])

In [77]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
b == c

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [80]:
a == c

array([[ True,  True,  True],
       [False, False, False]], dtype=bool)

In [81]:
(b == c) | (a == c)

array([[ True,  True,  True],
       [False, False, False]], dtype=bool)

In [82]:
(b == c) & (a == c)

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [83]:
b == c

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [84]:
np.allclose(b, c)

False

In [85]:
np.allclose(b, b)

True

In [86]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
c1 = np.arange(6).astype(np.float16).reshape([2, 3])

In [88]:
c1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float16)

In [89]:
np.allclose(c, c1)

True

In [90]:
c1[0, 0] = 2.0

In [91]:
c1

array([[ 2.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float16)

In [92]:
np.allclose(c, c1)

False

In [93]:
c == c1

array([[False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [94]:
np.all(c == c1)

False

In [95]:
np.allclose(c, c1, 2.1)

True