# この章の目的

NumPyで各種計算を行います。

## 内容

- UFunction
- BroadCast
- 内積

In [1]:
import numpy as np

In [2]:
a = np.arange(3)
b = np.arange(3, 9).reshape([2, 3])
c = np.arange(6).reshape([2, 3])
d = np.arange(6).reshape([3, 2])
e = np.arange(9).reshape([3, 3])

In [3]:
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[3 4 5]
 [6 7 8]]
c: [[0 1 2]
 [3 4 5]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)
print("e:", e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (3, 3)
